---
- name: Config |  Generate main config
  when: not ansible_check_mode
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
    owner: "{{ nginx_user }}"
  notify: Reload nginx

- name: Meta | Flush handlers
  ansible.builtin.meta: flush_handlers
