# SPDX-License-Identifier: MIT-0
---
# handlers file for nginx-role
- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Reload nginx
  ansible.builtin.command: nginx -s reload
  register: my_output
  changed_when: my_output.rc != 0
